[env:genericSTM32F411RE]
platform = ststm32
board = genericSTM32F411RE
framework = stm32cube
extra_scripts =
    pre:scripts/hard_float_link.py
    pre:scripts/strict_cpp_flags.py

build_unflags =
    -mfloat-abi=soft
    -mfloat-abi=softfp

build_flags =
    -I include
    -I include/bsp
    -I lib/FreeRTOS/include
    -I lib/FreeRTOS/portable
    -I include/core
    -I include/rtos_config
    -I include/hal
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16

[env:native]
platform = native
test_framework = unity
extra_scripts =
    pre:scripts/strict_cpp_flags.py
build_src_filter =
    -<*>

build_flags =
    -I include
    -I include/core
    -I include/hal
    -I test/mocks
    -DWASHIOS_ENABLE_TEST_HOOKS
