[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = stm32cube
monitor_speed = 115200
extra_scripts =
    pre:../core/scripts/strict_cpp_flags.py

build_flags =
    -I ../core/include/comms
    -I ../core/include/core

build_src_flags =
    -fno-use-cxa-atexit
