[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = stm32cube
monitor_speed = 115200
extra_scripts =
    pre:../core/scripts/strict_cpp_flags.py

build_flags =
    -I ../core/include/comms
    -I ../core/include/core

build_src_flags =
    -fno-use-cxa-atexit

[env:native]
platform = native
test_framework = unity
extra_scripts =
    pre:../core/scripts/strict_cpp_flags.py
build_src_filter =
    -<*>
build_flags =
    -I src
    -I ../core/include/comms

[env:nucleo_g474re_scope]
extends = env:nucleo_g474re
build_flags =
    ${env:nucleo_g474re.build_flags}
    -DICSEC_SCOPE_INSTRUMENTATION
