[env:nucleo_g431rb]
platform = ststm32
board = nucleo_g431rb
framework = stm32cube
board_build.ldscript = bootloader.ld
extra_scripts =
    pre:scripts/provision_slot_crc.py
    pre:../core/scripts/hard_float_link.py
    pre:../core/scripts/strict_cpp_flags.py

custom_washiboot_slot_a_elf = ../core/.pio/build/nucleo_g431rb/firmware.elf
custom_washiboot_slot_a_base = 0x08004000
custom_washiboot_slot_a_length = 0xE000

build_unflags =
    -mfloat-abi=soft
    -mfloat-abi=softfp

build_flags =
    -DSTM32G431xx
    -DWASHIOS_BARE_METAL
    -DWASHIOS_NO_EXCEPTIONS
    -I include
    -I ../core/include/core
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16

build_src_flags =
    -fno-use-cxa-atexit

upload_flags =
    -c
    reset_config none

[env:nucleo_g431rb_lasercom]
extends = env:nucleo_g431rb
custom_washiboot_slot_a_elf = ../core/.pio/build/nucleo_g431rb_lasercom/firmware.elf

[env:nucleo_g431rb_payload_demo]
extends = env:nucleo_g431rb
custom_washiboot_slot_a_elf = ../core/.pio/build/nucleo_g431rb_payload_demo/firmware.elf

[env:nucleo_g431rb_payload_demo_scope]
extends = env:nucleo_g431rb
custom_washiboot_slot_a_elf = ../core/.pio/build/nucleo_g431rb_payload_demo_scope/firmware.elf

[env:native]
platform = native
test_framework = unity
extra_scripts =
    pre:../core/scripts/strict_cpp_flags.py
build_src_filter =
    -<*>
build_flags =
    -I include
    -I ../core/include/core
    -DNATIVE
    -DWASHIBOOT_ENABLE_TEST_HOOKS
    -DWASHIBOOT_DEFAULT_EXPECTED_CRC32=0x00000000UL
